# Generated by Django 4.2 on 2023-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veg', '0003_receipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
